
import ChildBanner from '@/Component/Slider/ChildBanner';
import MegaSlider from '@/Component/Slider/MegaSlider';
import Head from 'next/head';
import { Card as BsCard, Card } from 'react-bootstrap';
import pulsLogo from '@/assets/pulsa.png';
import Image from 'next/image'
import CategorySlider from '@/Component/Slider/CategorySlider';
import MerkProduk from '@/Produk/MerkProduk';
import imgs from '@/assets/card_produks.png';
import BanerAdvertisment from '@/Advertisment/BanerAdvertisment';

export default function HomeIndex() {
  return (
    <>
      <Head>
        <title>Mangdropship Api</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid p-fluid mt-3">
        <div className="col-12">
          <div className="grid">
            <div className="col-12 md:col-9">
              <MegaSlider />
            </div>
            <div className="col-12 md:col-3 ps-1">
              <ChildBanner />
            </div>
          </div>
        </div>
        <div className="col-12">
          <div className="grid p-fluid">
            <div className="col-12 md:col-3">
              <BsCard className='border-0 shadow-sm' style={{ backgroundColor: 'orange' }}>
                <BsCard.Body style={{ height: '129px' }}>
                  <Image src={pulsLogo} alt='asnjfknjasnf' className='d-block mx-auto' />
                  <div className='text-center text-white fw-bold'>Pulsa dan Tagihan</div>
                </BsCard.Body>
              </BsCard>
            </div>
            <div className="col-12 md:col-9">
              <BsCard className='border-0 shadow-sm mang-light'>
                <BsCard.Body style={{ height: '129px' }}>
                  <CategorySlider />
                </BsCard.Body>
              </BsCard>
            </div>
          </div>
        </div>
        <div className="col-12">
          <MerkProduk />
        </div>
        <div className="col-12">
          <MerkProduk />
        </div>
        <div className="col-12">
           <BanerAdvertisment/>
        </div>
        <div className="col-12">
          <div className="grid">
            {
              Array(20).fill(0).map((__, idx) => (
                <div className="col-12 md:col-6 lg:col-2" key={idx}>
                  <Card className='border-0 shadow-sm' key={idx}>
                    <Image src={imgs} alt='asfadfaf' className='w-100' />
                    <Card.Body>
                      Lorem ipsum dolor sit amet.
                    </Card.Body>
                  </Card>
                </div>
              ))
            }
          </div>
        </div>
      </div>
    </>
  )
}

HomeIndex.getLayoutIndex = function (page: any) {
  return page;
}
